// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {models} from '../models';
import {main} from '../models';

export function AddTagToNote(arg1:number,arg2:number):Promise<void>;

export function BackupToDir():Promise<string>;

export function BatchAddTagToNotes(arg1:Array<number>,arg2:number):Promise<void>;

export function BatchDeleteNotes(arg1:Array<number>):Promise<void>;

export function BatchMoveNotesToNotebook(arg1:Array<number>,arg2:number):Promise<void>;

export function BatchPinNotes(arg1:Array<number>,arg2:boolean):Promise<void>;

export function BatchRemoveTagFromNotes(arg1:Array<number>,arg2:number):Promise<void>;

export function BatchRestoreNotes(arg1:Array<number>):Promise<void>;

export function CallAI(arg1:Array<services.Message>):Promise<string>;

export function CallAIStream(arg1:number,arg2:Array<services.Message>,arg3:boolean,arg4:boolean,arg5:boolean):Promise<void>;

export function CancelAIStream():Promise<void>;

export function ClearAISessionMessages(arg1:number):Promise<void>;

export function CreateAISession():Promise<number>;

export function CreateNote(arg1:string,arg2:string,arg3:string,arg4:number):Promise<models.Note>;

export function CreateNotebook(arg1:string):Promise<models.Notebook>;

export function CreateProfile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.APIProfile>;

export function CreateTag(arg1:string,arg2:string):Promise<models.Tag>;

export function DeleteAIMessage(arg1:number):Promise<void>;

export function DeleteAIMessagesAfter(arg1:number,arg2:number):Promise<number>;

export function DeleteAISession(arg1:number):Promise<void>;

export function DeleteNote(arg1:number):Promise<void>;

export function DeleteNotebook(arg1:number):Promise<void>;

export function DeleteNotebookWithNotes(arg1:number):Promise<void>;

export function DeleteProfile(arg1:number):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function EmptyTrash():Promise<void>;

export function EmptyTrashNotebooks():Promise<void>;

export function ExportAISessionAsMarkdown(arg1:number):Promise<string>;

export function ExportDataWithDialog():Promise<string>;

export function ExportNoteAsMarkdown(arg1:number):Promise<string>;

export function FetchAIModels(arg1:string,arg2:string):Promise<Array<string>>;

export function GetAIConfig():Promise<services.AIConfig>;

export function GetAIRefMaxChars():Promise<number>;

export function GetAISearchResultLimit():Promise<number>;

export function GetAISessions():Promise<Array<services.AISessionSummary>>;

export function GetAllNoteIDs():Promise<Array<number>>;

export function GetAllNotebooks():Promise<Array<models.Notebook>>;

export function GetAllTags():Promise<Array<models.Tag>>;

export function GetBackupInfo():Promise<Record<string, string>>;

export function GetDataStats():Promise<services.DataStats>;

export function GetNote(arg1:number):Promise<models.Note>;

export function GetNoteContent(arg1:number):Promise<string>;

export function GetNoteIDsByNotebook(arg1:number):Promise<Array<number>>;

export function GetNoteRefContext(arg1:Array<number>):Promise<services.NoteRefContext>;

export function GetNotebookNoteCounts():Promise<Record<number, number>>;

export function GetNotes(arg1:number,arg2:number,arg3:string,arg4:number):Promise<services.PaginatedResult>;

export function GetNotesByTag(arg1:number,arg2:number,arg3:number,arg4:string):Promise<services.PaginatedResult>;

export function GetPageSize():Promise<number>;

export function GetProfiles():Promise<Array<models.APIProfile>>;

export function GetSetting(arg1:string):Promise<string>;

export function GetSortOrder():Promise<string>;

export function GetSystemFonts():Promise<Array<string>>;

export function GetTrashNotebooks(arg1:number,arg2:number):Promise<services.PaginatedResult>;

export function GetTrashNotes(arg1:number,arg2:number):Promise<services.PaginatedResult>;

export function GetVersion():Promise<string>;

export function ImportDatabaseWithDialog():Promise<services.ImportResult>;

export function ImportFiles(arg1:Array<string>,arg2:number):Promise<Array<main.FileImportResult>>;

export function LoadAISessionMessages(arg1:number):Promise<Array<services.Message>>;

export function MoveNoteToNotebook(arg1:number,arg2:number):Promise<void>;

export function OpenDataDir():Promise<void>;

export function OpenProjectURL(arg1:string):Promise<string>;

export function PermanentDeleteNote(arg1:number):Promise<void>;

export function PermanentDeleteTrashNotebook(arg1:number):Promise<void>;

export function RemoveTagFromNote(arg1:number,arg2:number):Promise<void>;

export function RenameAISession(arg1:number,arg2:string):Promise<void>;

export function RenameNotebook(arg1:number,arg2:string):Promise<models.Notebook>;

export function ResetDatabase():Promise<void>;

export function RestoreAllNotes():Promise<void>;

export function RestoreAllTrashNotebooks():Promise<void>;

export function RestoreFromDir():Promise<services.ImportResult>;

export function RestoreNote(arg1:number):Promise<void>;

export function RestoreTrashNotebook(arg1:number):Promise<void>;

export function SaveAIConfig(arg1:services.AIConfig):Promise<void>;

export function SaveAIMessageAsNote(arg1:string):Promise<models.Note>;

export function SaveAIMessages(arg1:number,arg2:Array<services.Message>):Promise<void>;

export function SearchNotes(arg1:string,arg2:number,arg3:number,arg4:number,arg5:string,arg6:string,arg7:string,arg8:Array<number>):Promise<services.PaginatedResult>;

export function SetAIRefMaxChars(arg1:number):Promise<void>;

export function SetAISearchResultLimit(arg1:number):Promise<void>;

export function SetPageSize(arg1:number):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function SetSortOrder(arg1:string):Promise<void>;

export function SwitchProfile(arg1:number):Promise<void>;

export function TestAIBaseURL(arg1:string,arg2:string):Promise<boolean>;

export function TestTavilyConnection(arg1:string):Promise<boolean>;

export function TogglePinAISession(arg1:number):Promise<void>;

export function TogglePinNote(arg1:number):Promise<models.Note>;

export function UpdateAIMessageContent(arg1:number,arg2:string):Promise<void>;

export function UpdateNote(arg1:number,arg2:string,arg3:string,arg4:string):Promise<models.Note>;

export function UpdateNoteFileExt(arg1:number,arg2:string):Promise<models.Note>;

export function UpdateProfile(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function UpdateSessionContextTokens(arg1:number,arg2:number):Promise<void>;

export function UpdateTag(arg1:number,arg2:string,arg3:string):Promise<models.Tag>;

export function VacuumDatabase():Promise<string>;
