// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';

export function AddTagToNote(arg1:number,arg2:number):Promise<void>;

export function CreateNote(arg1:string,arg2:string,arg3:string):Promise<models.Note>;

export function CreateTag(arg1:string,arg2:string):Promise<models.Tag>;

export function DeleteNote(arg1:number):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function GetAllTags():Promise<Array<models.Tag>>;

export function GetNote(arg1:number):Promise<models.Note>;

export function GetNotes(arg1:number,arg2:number):Promise<services.PaginatedResult>;

export function GetNotesByTag(arg1:number,arg2:number,arg3:number):Promise<services.PaginatedResult>;

export function GetTrashNotes(arg1:number,arg2:number):Promise<services.PaginatedResult>;

export function PermanentDeleteNote(arg1:number):Promise<void>;

export function RemoveTagFromNote(arg1:number,arg2:number):Promise<void>;

export function RestoreNote(arg1:number):Promise<void>;

export function SearchNotes(arg1:string,arg2:number,arg3:number):Promise<services.PaginatedResult>;

export function TogglePinNote(arg1:number):Promise<models.Note>;

export function UpdateNote(arg1:number,arg2:string,arg3:string,arg4:string):Promise<models.Note>;

export function UpdateTag(arg1:number,arg2:string,arg3:string):Promise<models.Tag>;
