// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTagToNote(arg1, arg2) {
  return window['go']['main']['App']['AddTagToNote'](arg1, arg2);
}

export function BackupToDir() {
  return window['go']['main']['App']['BackupToDir']();
}

export function BatchAddTagToNotes(arg1, arg2) {
  return window['go']['main']['App']['BatchAddTagToNotes'](arg1, arg2);
}

export function BatchDeleteNotes(arg1) {
  return window['go']['main']['App']['BatchDeleteNotes'](arg1);
}

export function BatchRemoveTagFromNotes(arg1, arg2) {
  return window['go']['main']['App']['BatchRemoveTagFromNotes'](arg1, arg2);
}

export function BatchRestoreNotes(arg1) {
  return window['go']['main']['App']['BatchRestoreNotes'](arg1);
}

export function ClearDraft() {
  return window['go']['main']['App']['ClearDraft']();
}

export function CreateNote(arg1, arg2) {
  return window['go']['main']['App']['CreateNote'](arg1, arg2);
}

export function CreateTag(arg1, arg2) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function EmptyTrash() {
  return window['go']['main']['App']['EmptyTrash']();
}

export function ExportDataWithDialog() {
  return window['go']['main']['App']['ExportDataWithDialog']();
}

export function ExportNoteAsMarkdown(arg1) {
  return window['go']['main']['App']['ExportNoteAsMarkdown'](arg1);
}

export function GetAllNoteIDs() {
  return window['go']['main']['App']['GetAllNoteIDs']();
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetBackupInfo() {
  return window['go']['main']['App']['GetBackupInfo']();
}

export function GetDataStats() {
  return window['go']['main']['App']['GetDataStats']();
}

export function GetDraft() {
  return window['go']['main']['App']['GetDraft']();
}

export function GetNote(arg1) {
  return window['go']['main']['App']['GetNote'](arg1);
}

export function GetNotes(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetNotes'](arg1, arg2, arg3);
}

export function GetNotesByTag(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetNotesByTag'](arg1, arg2, arg3, arg4);
}

export function GetPageSize() {
  return window['go']['main']['App']['GetPageSize']();
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetSortOrder() {
  return window['go']['main']['App']['GetSortOrder']();
}

export function GetSystemFonts() {
  return window['go']['main']['App']['GetSystemFonts']();
}

export function GetTrashNotes(arg1, arg2) {
  return window['go']['main']['App']['GetTrashNotes'](arg1, arg2);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportDatabaseWithDialog() {
  return window['go']['main']['App']['ImportDatabaseWithDialog']();
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function OpenProjectURL(arg1) {
  return window['go']['main']['App']['OpenProjectURL'](arg1);
}

export function PermanentDeleteNote(arg1) {
  return window['go']['main']['App']['PermanentDeleteNote'](arg1);
}

export function RemoveTagFromNote(arg1, arg2) {
  return window['go']['main']['App']['RemoveTagFromNote'](arg1, arg2);
}

export function ResetDatabase() {
  return window['go']['main']['App']['ResetDatabase']();
}

export function RestoreAllNotes() {
  return window['go']['main']['App']['RestoreAllNotes']();
}

export function RestoreFromDir() {
  return window['go']['main']['App']['RestoreFromDir']();
}

export function RestoreNote(arg1) {
  return window['go']['main']['App']['RestoreNote'](arg1);
}

export function SaveDraft(arg1, arg2) {
  return window['go']['main']['App']['SaveDraft'](arg1, arg2);
}

export function SearchNotes(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchNotes'](arg1, arg2, arg3);
}

export function SetPageSize(arg1) {
  return window['go']['main']['App']['SetPageSize'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function SetSortOrder(arg1) {
  return window['go']['main']['App']['SetSortOrder'](arg1);
}

export function TogglePinNote(arg1) {
  return window['go']['main']['App']['TogglePinNote'](arg1);
}

export function UpdateNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2, arg3);
}

export function UpdateTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTag'](arg1, arg2, arg3);
}
